### ISSUE TITLE
Issue while loading website

### ISSUE THREAD

**Issue by SyedTahseen** [cheems/goindex-extended#14]
![Screenshot_20210919-145939](https://user-images.githubusercontent.com/53108646/133923480-f1489a5e-2252-4759-8ca8-39e7128284ce.png)
It happens for a moment while loading website, kindly fix it

**Comment by cheems** [comment]
Please specify a bit more. I think you've mentioned about the icons. does it only happen while loading or once happened, does it remain until reload the page again?

**Comment by SyedTahseen** [comment]
It happened when we first time load the website, or sometimes it happened, when website is fully loaded then it's fine and work well

**Comment by cheems** [comment]
This can be due to several reasons including the speed of the isp, cdn speed which is used to serve the icon pack. Also the size of the icon pack may impact on the time it takes to appear completely. Once the icon pack is loaded, browser cache will optimize the page loading.

At the moment I'm focused on the backend and my current goal is making the all files in the index accessible. After that I will try to have a look at the front end:)
