### ISSUE TITLE
slider missing in pc view of index

### ISSUE THREAD

**Issue by AmirulAndalib** [cheems/goindex-extended#20]
in pc view the silder for sliding down the page is missing

but in mobile view its present
![Screenshot (3219)](https://user-images.githubusercontent.com/86344856/135826368-807c2507-3060-4e19-9745-5d7b8a0cee92.jpg)

**Comment by cheems** [comment]
Fixed! Actually, in the initial code, it was hidden intentionally using `::-webkit-scrollbar CSS pseudo-element` which isn't [compatible with Firefox browser](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar#-webkit-scrollbar). So it doesn't hide the scrollbar on Firefox. Since I'm also using Firefox I didn't experience the issue. Anyways thank you for mentioning the issue.

Please update the line: 190 in your index code by replacing the link to app.js with the latest commit. You can find the updated link from here: [index.js#L190](https://github.com/cheems/goindex-extended/blob/85af3c137cd430a8cb2c0ebaee60e983c2579223/index.js#L190)
