### ISSUE TITLE
Can we change siteTitle to current video/audio being played?

### ISSUE THREAD

**Issue by askfriends** [cheems/goindex-extended#22]
hi;
can we change site title to current audio/video's name being played?
for example if im at MainSite/folder/anotherfolder/audio.mp3
than site title should be audio,mp3
OR
audio.mp3 - MainSite

Similarly for all file types.

**Comment by askfriends** [comment]
> Added! Get the latest [index.js](https://github.com/cheems/goindex-extended/blob/master/index.js) file and set values in [line: 88](https://github.com/cheems/goindex-extended/blob/557e1cb2d05c0a39f59dbb9ce09c0c20a604727b/index.js#L88) and [line: 89](https://github.com/cheems/goindex-extended/blob/557e1cb2d05c0a39f59dbb9ce09c0c20a604727b/index.js#L89) to true as you need.
> 
> If you set `"title_include_drive_name"` to true, then it will add current drive name to the page title.
> 
> > Ex: GoIndex Extended - Disk 01
> 
> If you set `"title_include_path"` to true, then it will add the current path to the page title, and if you are in the preview page, it will add the opened file name to the page title.
> 
> > Ex: GoIndex Extended - /Multimedia/Images/
> > Ex: GoIndex Extended - waifu01.png
> 
> If you set both values to true, then the title will look like this:
> 
> > Ex: GoIndex Extended - Disk 01 - waifu01.png
> 
> Check the demo index to see how it works.

Thank you so much for quick response and implementation.
I just checked the demo and it works!

But i wonder if we have long path than it will look messy, So can you add another option to just show drive name + current path only
For example: If we are at MYGdrive/my-collection/audio-songs/arttist-name/album/songbeingplayed.mp3
It should show MYGdrive - songbeingplayed.mp3 only

**Comment by cheems** [comment]
Added!
Check latest [index.js](https://github.com/cheems/goindex-extended/blob/master/index.js)

**Comment by cheems** [comment]
It works fine.
If it doesn't work, probably it can be due to missconfiguration.
Check the instructions written in the code: [Line:89-92](https://github.com/cheems/goindex-extended/blob/f0d11a61b2d8d61618babb327fed22761a0ed9bb/index.js#L89)

Here you can find working examples.

**Only the current directory, only the file name when in the preview page**
https://dark-demo.dudoo.workers.dev
![image](https://user-images.githubusercontent.com/28010975/136676096-8bffe132-ef72-42d1-a196-9e51dc531e0f.png)



**Full path, only the file name when in the preview page**
https://light-demo.dudoo.workers.dev
![image](https://user-images.githubusercontent.com/28010975/136676109-08288fc2-960d-44c7-8bd0-5e6b470353ac.png)

**Comment by askfriends** [comment]
> It works fine. If it doesn't work, probably it can be due to missconfiguration. Check the instructions written in the code: [Line:89-92](https://github.com/cheems/goindex-extended/blob/f0d11a61b2d8d61618babb327fed22761a0ed9bb/index.js#L89)
> 
> Here you can find working examples.
> 
> **Only the current directory, only the file name when in the preview page** https://dark-demo.dudoo.workers.dev ![image](https://user-images.githubusercontent.com/28010975/136676096-8bffe132-ef72-42d1-a196-9e51dc531e0f.png)
> 
> **Full path, only the file name when in the preview page** https://light-demo.dudoo.workers.dev ![image](https://user-images.githubusercontent.com/28010975/136676109-08288fc2-960d-44c7-8bd0-5e6b470353ac.png)

yeah bro thanks i just set it to `current-directory` and it works.
Please add this config in wiki as well so that everyone can find this easily
