### ISSUE TITLE
DMCA question

### ISSUE THREAD

**Issue by scese250** [cheems/goindex-extended#24]
Hi! It's just a question. I'm wondering if my Google Drive could ever getting dmca'd by using GoIndex. 
I supuse CloudFlare could close my account, which wouldn't be a problem since I can create other account and the only information about my Google Drive is just my API.

**Comment by cheems** [comment]
According to my knowledge, since this project doesn't violate any terms of services, it won't cause any DMCA infringement(until you don't share any copyrighted materials). And even if someone shares that kind of files using Goindex, an average visitor still cannot know whom this drive belongs to because Google Drive API doesn't let users get metadata for files that they don't have access to. But not sure if someone from the staff can check the owner by file ids which can be obtained using inspect element or checking network tab. However, a normal user can still report Google by providing the URL of the index.

The reason for including file ids in the front end is using them to get results for search queries. However, I already planned to implement an encryption option that encrypts ids before sending them to the frontend. Then the thing mentioned above also will not be possible.
