### ISSUE TITLE
Stream in App, Stream MKV directly problem

### ISSUE THREAD

**Issue by KevinNitroG** [cheems/goindex-extended#47]
It seems that the MKV with multi subs or audios can't be loaded. And some MKV can't load the video either.
Secondly, I can't use MXPlayer on my phone to network stream the video.
That will be so extremely nice if you change the player to Plyr, can stream all the MKV in web with captions <3 Thank you for your open source!

**Comment by cheems** [comment]
Thank you for your appreciation. Plyr video player, multiple subtitle files support, both srt, vtt support are already implemented and tested. But due to the lack of free time, I couldn't push the update. It will be pushed shortly.

When it comes to MKV files, if they are in x265, they cannot be played with the usual HTML5 player. (Plyr is just a skin for the basic html5 player). But you can play them with a 3rd party players and that option can be found on video pages. Also, you can play them with Microsoft's Edge if you have purchased [their HEVC plugin](https://www.microsoft.com/en-us/p/hevc-video-extensions/9nmzlz57r3t7). But I spotted once that they can be played with mobile browsers like Google Chrome.

PC browsers such as Firefox, Chrome will not support HEVC while it is encumbered by patents. [[bug 1332136](https://bugzilla.mozilla.org/show_bug.cgi?id=1332136)]
